name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 5 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    environment:
      name: production
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: setting/setting.json
      - name: Commit & Push
        run: |
          git config user.name slowerthan5cmpersec
          git config user.email slowerthan5cmpersec@gmail.com
          git add -A .
          if git commit -m "generated"; then
            git push
          fi
