# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: my-metrics-0.svg
          
          user: slowerthan5cmpersec
          template: classic
          base: header, activity, repositories
          extras_js: |
            document.querySelectorAll("h1")?.forEach(h1 => h1.innerHTML = "҂ ⬝_-) ᡕᠵᡁデ╤═╾╼   ✛");

            const rects = document.querySelectorAll("rect");
            rects.forEach(rect => {
              var color = rect.getAttribute("fill");
              if (color == "#ebedf0") {
                rect.setAttribute("fill", "#f8f8f2");
              } 
              else if (color == "#216e39") {
                rect.setAttribute("fill", "#191A21");
              } 
              else if (color == "#30a14e") {
                rect.setAttribute("fill", "#44475a");
              } 
              else if (color == "#40c463") {
                rect.setAttribute("fill", "#ff79c6");
              } 
              else if (color == "#9be9a8") {
                rect.setAttribute("fill", "#8be9fd");
              } 
            });
            
          config_timezone: Asia/Seoul
          extras_css: |
            h1 {
              color: #ff79c6;
            }
            h2 {
              color: #8be9fd;
            }
            h3 {
              color: #ff79c6;
            }          

            

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: my-metrics-1.svg

          user: slowerthan5cmpersec
          template: classic
          base: ''
          extras_js: |
            const paths = document.querySelectorAll("path");
            paths.forEach(path => {
              var color = path.getAttribute("fill");
              if (color == "#ebedf0") {
                path.setAttribute("fill", "#f8f8f2");
              } 
              else if (color == "#216e39") {
                path.setAttribute("fill", "#191A21");
              } 
              else if (color == "#30a14e") {
                path.setAttribute("fill", "#44475a");
              } 
              else if (color == "#40c463") {
                path.setAttribute("fill", "#ff79c6");
              } 
              else if (color == "#9be9a8") {
                path.setAttribute("fill", "#8be9fd");
              } 
            });
              
          config_timezone: Asia/Seoul
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          extras_css: |
            h1 {
              color: #8be9fd;
            }
            h2 {
              color: #ff79c6;
            }
            h3 {
              color: #8be9fd;
            }

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: my-metrics-2.svg

          user: slowerthan5cmpersec
          template: classic
          base: ""
          config_timezone: Asia/Seoul
          plugin_languages: yes
          plugin_languages_aliases: Jupyter Notebook:Jupyter
          plugin_languages_analysis_timeout: 10
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 180
          plugin_languages_recent_load: 600
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          extras_css: |
            h1 {
              color: #8be9fd;
            }
            h2 {
              color: #8be9fd;
            }
            h3 {
              color: #8be9fd;
            }



      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: my-metrics-3.svg

          user: slowerthan5cmpersec
          template: classic
          base: ""
          config_timezone: Asia/Seoul
          plugin_habits: yes
          plugin_habits_days: 15
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          extras_css: |
            h1 {
              color: #ff79c6;
            }
            h2 {
              color: #8be9fd;
            }
            h3 {
              color: #ff79c6;
            }
