# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: my-metrics-0.svg
          
          user: slowerthan5cmpersec
          template: classic
          base: header, activity, repositories
          extras_js: |
            document.querySelectorAll("h1")?.forEach(h1 => h1.innerHTML = "҂ ╸_-) ᡕᠵᡁデ╤═╾╼━    ✛")
          config_timezone: Asia/Seoul
          extras_css: |
            h1 {
              color: #ff79c6;
            }
            h2 {
              color: #8be9fd;
            }
            h3 {
              color: #ff79c6;
            }          

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: my-metrics-1.svg

          user: slowerthan5cmpersec
          template: classic
          base: ''
          config_timezone: Asia/Seoul
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          extras_css: |
            h1 {
              color: #ff79c6;
            }
            h2 {
              color: #8be9fd;
            }
            h3 {
              color: #ff79c6;
            }

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: my-metrics-2.svg

          user: slowerthan5cmpersec
          template: classic
          base: ""
          config_timezone: Asia/Seoul
          plugin_languages: yes
          plugin_languages_analysis_timeout: 10
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          extras_css: |
            h1 {
              color: #ff79c6;
            }
            h2 {
              color: #8be9fd;
            }
            h3 {
              color: #ff79c6;
            }



      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: my-metrics-3.svg

          user: slowerthan5cmpersec
          template: classic
          base: ""
          config_timezone: Asia/Seoul
          plugin_habits: yes
          plugin_habits_charts_type: chartist
          plugin_habits_days: 15
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          extras_css: |
            h1 {
              color: #ff79c6;
            }
            h2 {
              color: #8be9fd;
            }
            h3 {
              color: #ff79c6;
            }
